Feat/2822 write files in json
kids-first/kf-portal-etl pull request #140
Opened 2021-01-28 19:38 UTC by adipaul1981

2021-01-28 19:44 UTC, jecos requested changes

2021-01-28 19:44 UTC, jecos commented on src/main/scala/io/kf/etl/ETLMain.scala
> +  val saveJsonToS3: Boolean = Try(saveJsonFiles.toBoolean).getOrElse(false)
instead having a new parameter, could we relied on the same config that conatinas the filepath?

2021-01-28 19:44 UTC, jecos commented on src/test/scala/io/kf/etl/processors/participantcommon/transform/step/WriteJsonSinkTest.scala
> +    val directory = new Directory(new File("./src/test/json_output/file_centric_study1_release1"))
use getClass().getRessource(...) instead

2021-01-28 19:44 UTC, jecos commented on src/test/scala/io/kf/etl/processors/participantcommon/transform/step/WriteJsonSinkTest.scala
> +  "process" should "merge phenotypes and participant" in {
Not sure the test is relevant

2021-01-28 19:46 UTC, botekchristophe approved these changes

2021-01-28 19:47 UTC, jecos requested changes

2021-01-28 19:47 UTC, jecos commented on src/main/scala/io/kf/etl/processors/participantcommon/transform/step/WriteJsonSink.scala
>    def apply[T](processorName: String)(step: String)(input: Dataset[T])(implicit config: Config, spark: SparkSession): Dataset[T] = {
I would verify if this class is already used. If not, I would rather implement export to jsin directly into JsonOutputProcessor and delete this class

2021-01-29 15:34 UTC, jecos requested changes

2021-01-29 15:34 UTC, jecos commented on src/main/scala/io/kf/etl/ETLMain.scala
> +    val saveJsonToS3 = Try(config.getBoolean(SAVE_JSON_FILES)).getOrElse(false)
Maybe we could have only one env var :
```
     val saveJsonToS3 = Try(config.getString(JSON_OUTPUT_FILES)).map(s=> s!= null && s.nonEmpty).getOrElse(false)  
```

2021-01-29 16:16 UTC, merged